export const PROJECTS = [
  {
    slug: "toa-nha-van-phong-dong-a",
    title: "Tòa nhà văn phòng Đông Á",
    category: "Dân dụng",
    location: "TP. Hồ Chí Minh",
    client: "Công ty CP Đầu tư Đông Á",
    year: 2023,
    status: "COMPLETED",
    scope: "Thi công trọn gói",
    shortDescription: "Tòa nhà văn phòng 12 tầng với tổng diện tích sàn hơn 15.000 m², hoàn thiện theo tiêu chuẩn cao cấp.",
    content: "<p>Dự án tòa nhà văn phòng Đông Á là một trong những công trình tiêu biểu của chúng tôi trong lĩnh vực dân dụng cao tầng.</p><p>Công trình gồm 12 tầng nổi và 2 tầng hầm, kết cấu bê tông cốt thép, mặt dựng kính hiện đại.</p><h3>Phạm vi công việc</h3><ul><li>Thi công phần móng và tầng hầm</li><li>Kết cấu thân và hoàn thiện</li><li>Hệ thống MEP toàn bộ tòa nhà</li><li>Cảnh quan và hạ tầng kỹ thuật</li></ul>",
    featured: true,
  },
  {
    slug: "nha-xuong-khu-cong-nghiep-long-an",
    title: "Nhà xưởng khu công nghiệp Long An",
    category: "Công nghiệp",
    location: "Long An",
    client: "Công ty TNHH Sản xuất Long Hậu",
    year: 2022,
    status: "COMPLETED",
    scope: "Thiết kế & thi công",
    shortDescription: "Nhà xưởng sản xuất kết cấu thép tiền chế với diện tích 8.000 m², đáp ứng tiêu chuẩn công nghiệp nặng.",
    content: "<p>Dự án nhà xưởng tại KCN Long An được thiết kế và thi công bởi đội ngũ kỹ sư giàu kinh nghiệm của Đông Á.</p><p>Công trình sử dụng kết cấu thép tiền chế, mái tôn cách nhiệt, hệ thống thông gió công nghiệp.</p>",
    featured: false,
  },
  {
    slug: "cau-duong-dong-nai",
    title: "Cầu đường Đồng Nai",
    category: "Hạ tầng",
    location: "Đồng Nai",
    client: "Sở GTVT Đồng Nai",
    year: 2024,
    status: "COMPLETED",
    scope: "Thi công xây dựng",
    shortDescription: "Cầu bê tông cốt thép dài 220m cùng tuyến đường dẫn 2,5km phục vụ phát triển kinh tế địa phương.",
    content: "<p>Dự án cầu đường tại Đồng Nai là công trình hạ tầng trọng điểm, kết nối các khu vực kinh tế trọng điểm.</p>",
    featured: false,
  },
  {
    slug: "biet-thu-nghi-duong-vung-tau",
    title: "Biệt thự nghỉ dưỡng Vũng Tàu",
    category: "Dân dụng",
    location: "Bà Rịa - Vũng Tàu",
    client: "Khách hàng cá nhân",
    year: 2023,
    status: "COMPLETED",
    scope: "Thiết kế & thi công",
    shortDescription: "Biệt thự nghỉ dưỡng 3 tầng với thiết kế hiện đại, hòa mình vào thiên nhiên ven biển.",
    content: "<p>Biệt thự được thiết kế theo phong cách tối giản, sử dụng vật liệu tự nhiên, tối ưu ánh sáng và gió biển.</p>",
    featured: false,
  },
  {
    slug: "nha-may-che-bien-binh-duong",
    title: "Nhà máy chế biến Bình Dương",
    category: "Công nghiệp",
    location: "Bình Dương",
    client: "Công ty CP Thực phẩm Bình Dương",
    year: 2021,
    status: "COMPLETED",
    scope: "Thi công trọn gói",
    shortDescription: "Nhà máy chế biến thực phẩm đạt chuẩn ISO 22000 với dây chuyền sản xuất hiện đại.",
    content: "<p>Nhà máy được thiết kế đáp ứng tiêu chuẩn vệ sinh an toàn thực phẩm ISO 22000, hệ thống xử lý nước thải đạt chuẩn.</p>",
    featured: false,
  },
  {
    slug: "he-thong-cap-nuoc-tay-ninh",
    title: "Hệ thống cấp nước Tây Ninh",
    category: "Hạ tầng",
    location: "Tây Ninh",
    client: "UBND tỉnh Tây Ninh",
    year: 2022,
    status: "COMPLETED",
    scope: "Thi công xây dựng",
    shortDescription: "Hệ thống cấp nước sạch quy mô 20.000 m³/ngày đêm phục vụ dân sinh khu vực.",
    content: "<p>Hệ thống cấp nước được thi công theo công nghệ hiện đại, đảm bảo chất lượng nước đạt chuẩn Bộ Y tế.</p>",
    featured: false,
  },
] as const;

export const ARTICLES = [
  {
    slug: "xu-huong-vat-lieu-xay-dung-2026",
    title: "Xu hướng vật liệu xây dựng bền vững năm 2026",
    excerpt: "Tổng quan các loại vật liệu thân thiện môi trường đang được ứng dụng rộng rãi trong ngành xây dựng hiện đại.",
    category: "Kiến thức",
    publishedAt: new Date("2026-01-15"),
    content: "<p>Năm 2026 đánh dấu sự chuyển dịch mạnh mẽ của ngành xây dựng Việt Nam sang các vật liệu bền vững và thân thiện môi trường.</p><h3>1. Bê tông xanh</h3><p>Bê tông sử dụng tro bay, xỉ lò cao thay thế một phần xi măng giúp giảm phát thải CO₂ đáng kể.</p><h3>2. Gạch không nung</h3><p>Gạch không nung từ tro xỉ nhiệt điện đang dần thay thế gạch đất sét nung truyền thống.</p><h3>3. Vật liệu tái chế</h3><p>Gỗ tái chế, nhựa tái chế composite được ứng dụng trong nội thất và vách ngăn.</p>",
  },
  {
    slug: "kinh-nghiem-chon-nha-thau",
    title: "Kinh nghiệm chọn nhà thầu xây dựng uy tín",
    excerpt: "Những tiêu chí quan trọng giúp chủ đầu tư lựa chọn đơn vị thi công phù hợp và tránh rủi ro.",
    category: "Kinh nghiệm",
    publishedAt: new Date("2026-02-20"),
    content: "<p>Chọn nhà thầu là quyết định quan trọng, ảnh hưởng đến chất lượng và tiến độ công trình.</p><h3>1. Năng lực pháp lý</h3><p>Kiểm tra giấy phép kinh doanh, chứng chỉ hành nghề xây dựng.</p><h3>2. Kinh nghiệm thực tế</h3><p>Xem các dự án đã hoàn thành, đến tận nơi kiểm tra chất lượng.</p><h3>3. Năng lực tài chính</h3><p>Đảm bảo nhà thầu có đủ nguồn lực tài chính để triển khai dự án.</p><h3>4. Hợp đồng rõ ràng</h3><p>Điều khoản tiến độ, thanh toán, bảo hành phải cụ thể và minh bạch.</p>",
  },
  {
    slug: "quy-trinh-thi-cong-an-toan",
    title: "Quy trình thi công an toàn theo tiêu chuẩn",
    excerpt: "Các bước đảm bảo an toàn lao động trong suốt quá trình thi công công trình xây dựng.",
    category: "Kỹ thuật",
    publishedAt: new Date("2026-03-10"),
    content: "<p>An toàn lao động là ưu tiên hàng đầu trong mọi công trình xây dựng.</p><h3>Đánh giá rủi ro</h3><p>Trước khi khởi công, đội an toàn phải đánh giá toàn bộ rủi ro tiềm ẩn.</p><h3>Trang bị bảo hộ</h3><p>Toàn bộ công nhân phải được trang bị đầy đủ mũ, giày, găng, dây an toàn.</p><h3>Đào tạo định kỳ</h3><p>Tổ chức huấn luyện an toàn lao động định kỳ cho toàn bộ nhân sự công trường.</p>",
  },
  {
    slug: "bao-gia-xay-dung-nha-o-2026",
    title: "Báo giá xây dựng nhà ở 2026: Những điều cần biết",
    excerpt: "Phân tích các yếu tố ảnh hưởng đến chi phí xây dựng nhà ở và cách lập dự toán hợp lý.",
    category: "Kinh nghiệm",
    publishedAt: new Date("2026-04-05"),
    content: "<p>Chi phí xây dựng nhà ở phụ thuộc vào nhiều yếu tố: diện tích, vật liệu, kết cấu, vị trí.</p><h3>Các yếu tố chính</h3><ul><li>Diện tích xây dựng</li><li>Loại vật liệu (phổ thông / trung cấp / cao cấp)</li><li>Kết cấu móng (móng đơn / móng cọc)</li><li>Yêu cầu về nội thất</li></ul>",
  },
  {
    slug: "chong-tham-cong-trinh-hieu-qua",
    title: "Chống thấm công trình hiệu quả: Kỹ thuật và vật liệu",
    excerpt: "Hướng dẫn chi tiết về các phương pháp chống thấm hiệu quả cho các loại công trình khác nhau.",
    category: "Kỹ thuật",
    publishedAt: new Date("2026-05-12"),
    content: "<p>Chống thấm là công tác quan trọng đảm bảo tuổi thọ và chất lượng công trình.</p><h3>Vật liệu chống thấm phổ biến</h3><ul><li>Màng bitum tự dính</li><li>Sơn chống thấm gốc PU</li><li>Vữa chống thấm gốc xi măng</li><li>Màng TPO/PVC</li></ul>",
  },
  {
    slug: "quan-ly-tien-do-thi-cong",
    title: "Quản lý tiến độ thi công: Phương pháp và công cụ",
    excerpt: "Các phương pháp quản lý tiến độ hiệu quả giúp công trình đúng hạn và tiết kiệm chi phí.",
    category: "Kinh nghiệm",
    publishedAt: new Date("2026-06-18"),
    content: "<p>Quản lý tiến độ tốt giúp tránh phát sinh chi phí và đảm bảo chất lượng công trình.</p><h3>Phương pháp phổ biến</h3><ul><li>Sơ đồ Gantt</li><li>Phương pháp đường găng (CPM)</li><li>Quản lý theo chu kỳ (Agile construction)</li></ul>",
  },
] as const;